### ISSUE TITLE
Tool doesn't work anymore?

### ISSUE THREAD

**Issue by thisisathrowaway10032021** [y2361547758/EbixExtract#9]
I just updated Ebookjapan's app and I noticed that any extraction doesn't work anymore. I get errors that say

"Unhandled Exception: EbiJALibrary.EbiExtractException: Decode error: EbiExtractException (FileOpenError)
   at EbiJALibrary.EbixBook.Init(String filePath, String keyFolder, String envid)
   at EbiJALibrary.EbixBook..ctor(String filePath)
   at ConsoleApp1.Program.Main(String[] args)
  "

My computer doesn't have any compiling tools so I can't actually compile a new version myself, so if possible could the code here on GitHub be fixed?

**Comment by ag3601** [comment]
remove [], leave just path
